create table if not exists students (
  id bigint generated by default as identity primary key,
  student_number text unique not null,
  first_name text not null,
  last_name text not null,
  email text,
  program text not null default 'BSIT',
  year_level integer not null default 1,
  is_irregular integer not null default 0,
  is_shifter integer not null default 0,
  password_hash text not null,
  password_salt text not null,
  qr_token text unique not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists admins (
  id bigint generated by default as identity primary key,
  username text unique not null,
  full_name text not null,
  role text not null default 'staff',
  password_hash text not null,
  password_salt text not null,
  created_at timestamptz not null default now()
);

create table if not exists subjects (
  id text primary key,
  code text unique not null,
  name text not null,
  units integer not null,
  year_level integer not null,
  sem integer not null,
  created_at timestamptz not null default now()
);

create table if not exists prerequisites (
  subject_id text not null references subjects(id) on delete cascade,
  prerequisite_id text not null references subjects(id) on delete cascade,
  primary key (subject_id, prerequisite_id)
);

create table if not exists sections (
  id bigint generated by default as identity primary key,
  subject_id text not null references subjects(id) on delete cascade,
  section_code text not null default 'A',
  day text not null,
  start_time time not null,
  end_time time not null,
  room text,
  instructor text,
  term text not null default '2026-2027-1'
);

create table if not exists student_subjects (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  subject_id text not null references subjects(id) on delete cascade,
  status text not null default 'completed',
  term text,
  grade text,
  updated_at timestamptz not null default now(),
  unique (student_id, subject_id)
);

create table if not exists study_plans (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  term text not null,
  plan_json text not null,
  total_units integer not null,
  status text not null default 'draft',
  created_at timestamptz not null default now()
);

create table if not exists enrollments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  section_id bigint not null references sections(id) on delete cascade,
  term text not null,
  status text not null default 'enrolled',
  created_at timestamptz not null default now()
);

create table if not exists qr_scans (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  admin_id bigint references admins(id),
  scanned_at timestamptz not null default now()
);

create table if not exists evaluations (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  generated_by bigint references admins(id),
  snapshot_json text not null,
  printed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists ai_conversations (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  status text not null default 'open',
  escalated integer not null default 0,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_reason text
);

create table if not exists ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references ai_conversations(id) on delete cascade,
  sender text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists concerns (
  id bigint generated by default as identity primary key,
  conversation_id bigint references ai_conversations(id) on delete set null,
  student_id bigint not null references students(id) on delete cascade,
  summary text not null,
  status text not null default 'open',
  admin_id bigint references admins(id),
  admin_notes text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists import_logs (
  id bigint generated by default as identity primary key,
  kind text not null,
  filename text,
  rows_ok integer not null default 0,
  rows_failed integer not null default 0,
  admin_id bigint references admins(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_student_subjects_student on student_subjects(student_id);
create index if not exists idx_sections_subject on sections(subject_id);
create index if not exists idx_ai_messages_conv on ai_messages(conversation_id);
create index if not exists idx_concerns_status on concerns(status);
create index if not exists idx_students_qr on students(qr_token);

create or replace function execute_sql(query text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if lower(ltrim(query)) like 'select%'
     or lower(ltrim(query)) like 'with%' then
    execute format(
      'select coalesce(jsonb_agg(to_jsonb(rows)), ''[]''::jsonb) from (%s) rows',
      query
    ) into result;
  elsif lower(ltrim(query)) like 'insert%' then
    execute format(
      'with inserted as (%s) select coalesce(jsonb_agg(to_jsonb(rows)), ''[]''::jsonb) from inserted rows',
      query
    ) into result;
  else
    execute query;
    result := '[]'::jsonb;
  end if;
  return result;
end;
$$;

revoke execute on function execute_sql(text) from public, anon, authenticated;
grant execute on function execute_sql(text) to service_role;
